steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/credit-scoring-service', '.']

  # push the container image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/credit-scoring-service']

  # deploy the container image to cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args: ['run',
              'deploy',
              'credit-scoring-service',
              '--image',
              'gcr.io/$PROJECT_ID/credit-scoring-service',
              '--region',
              'us-central1',
              '--platform',
              'managed',
              '--allow-unauthenticated']
    env:
      - '_USER_SERVICE_URL=user-service.mekar-test.xyz'

images: ['gcr.io/$PROJECT_ID/credit-scoring-service']
